AAX_CMonolithicParameters Class Reference
#include <AAX_CMonolithicParameters.h>
Description
Extension of the AAX_CEffectParameters class for monolithic VIs and effects.
This extension to AAX_CEffectParameters adds some conveniences for Virtual Instrument (VI) plug-ins and for other plug-ins that use a monolithic processing object, i.e. an object that combines state data with the audio render routine in a single object.
The RenderAudio method provides a direct audio processing callback within the data model object. Perform all audio processing in this method.
The StaticDescribe method establishes a generic MIDI processing context for the Effect. Call this method from the plug-in's Description callback implementation.
The AddSynchronizedParameter method provides a mechanism for synchronizing parameter updates with the real-time thread, allowing deterministic, accurate automation playback. For more information abou this feature, see Fixing timing issues due to shared data
Note
This convenience class assumes a monolithic processing environment (i.e. AAX_eConstraintLocationMask_DataModel .) This precludes the use of AAX_CMonolithicParameters -derived Effects in distributed-processing formats such as AAX DSP.
Public Member Functions
AAX_CMonolithicParameters (void)
~AAX_CMonolithicParameters (void) AAX_OVERRIDE
Protected Types
typedef std::pair< AAX_CParamID const, const AAX_IParameterValue * > TParamValPair
Protected Member Functions
 Real-time functions
Virtual functions called on the real-time thread
virtual void RenderAudio (AAX_SInstrumentRenderInfo *ioRenderInfo, const TParamValPair *inSynchronizedParamValues[], int32_t inNumSynchronizedParamValues)
 Configuration methods
void AddSynchronizedParameter (const AAX_IParameter &inParameter)
Convenience Layer Methods
Note
You should not need to override these methods, but if you do, make sure to call into the base class.
AAX_Result UpdateParameterNormalizedValue (AAX_CParamID iParamID, double aValue, AAX_EUpdateSource inSource) AAX_OVERRIDE
Updates a single parameter's state to its current value.
AAX_Result GenerateCoefficients () AAX_OVERRIDE
Generates and dispatches new coefficient packets.
AAX_Result ResetFieldData (AAX_CFieldIndex iFieldIndex, void *oData, uint32_t iDataSize) const AAX_OVERRIDE
Called by the host to reset a private data field in the plug-in's algorithm.
AAX_Result TimerWakeup () AAX_OVERRIDE
Periodic wakeup callback for idle-time operations.
static AAX_Result StaticDescribe (AAX_IEffectDescriptor *ioDescriptor, const AAX_SInstrumentSetupInfo &setupInfo)
static void AAX_CALLBACK StaticRenderAudio (AAX_SInstrumentRenderInfo *const inInstancesBegin [], const void *inInstancesEnd)
Additional Inherited Members
Member Typedef Documentation
TParamValPair
typedef std::pair<AAX_CParamID const, const AAX_IParameterValue*> AAX_CMonolithicParameters::TParamValPair [protected]
Constructor & Destructor Documentation
AAX_CMonolithicParameters()
AAX_CMonolithicParameters::AAX_CMonolithicParameters (void)
 AAX_CMonolithicParameters()
AAX_CMonolithicParameters::~AAX_CMonolithicParameters (void)
Member Function Documentation
RenderAudio()
virtual void AAX_CMonolithicParameters::RenderAudio (AAX_SInstrumentRenderInfo * ioRenderInfo, const TParamValPair * inSynchronizedParamValues[], int32_t inNumSynchronizedParamValues) [inline], [protected], [virtual]
Perform audio render
Parameters
 in,out ioRenderInfo State data for the current render buffer
 in inSynchronizedParamValues The parameter values which should be applied for the current render buffer
See also
AddSynchronizedParameter
Parameters
 in inNumSynchronizedParamValues The number of parameter values provided in inSynchronizedParamValues
Referenced by StaticRenderAudio().
AddSynchronizedParameter()
void AAX_CMonolithicParameters::AddSynchronizedParameter (const AAX_IParameter & inParameter) [protected]
Add a parameter for state synchronization
A parameter should be added for synchronization if:
It is important for the parameter's automation to be applied at the correct point on the timeline
It is possible to quickly update the plug-in's state to reflect a parameter change
See Parameter update timing for more information
Parameters
 in inParameter The parameter to be synchronized. This string will be copied internally and is not required to persist
References AAX_ASSERT, AAX_IParameter::Automatable(), AAX_IParameter::Identifier(), and kSynchronizedParameterQueueSize.
UpdateParameterNormalizedValue()
AAX_Result AAX_CMonolithicParameters::UpdateParameterNormalizedValue (AAX_CParamID iParameterID, double iValue, AAX_EUpdateSource iSource) [virtual]
Updates a single parameter's state to its current value.
Note
Do not call this method from the plug-in. This method should be called by the host only. To set parameter values from within the plug-in, use the AAX_IParameter interface.
Todo
Todo FLAGGED FOR CONSIDERATION OF REVISION
Parameters
 in iParameterID The ID of the parameter that is being updated
 in iValue The parameter's current value, to which its internal state must be updated
 in iSource The source of the update
Reimplemented from AAX_CEffectParameters.
References AAX_SUCCESS, AAX_CParameterManager::GetParameterByID(), AAX_CEffectParameters::mParameterManager, and AAX_CEffectParameters::UpdateParameterNormalizedValue().
GenerateCoefficients()
AAX_Result AAX_CMonolithicParameters::GenerateCoefficients () [virtual]
Generates and dispatches new coefficient packets.
This method is responsible for updating the coefficient packets associated with all parameters whose states have changed since the last call to GenerateCoefficients(). The host may call this method once for every parameter update, or it may `batch` parameter updates such that changes for several parameters are all handled by a single call to GenerateCoefficients().
For more information on tracking parameters' statuses using the AAX_CPacketDispatcher, helper class, see AAX_CPacketDispatcher::SetDirty().
Note
Do not call this method from the plug-in. This method should be called by the host only. To set parameter values from within the plug-in, use the AAX_IParameter interface.
Reimplemented from AAX_CEffectParameters.
References AAX_ASSERT, AAX_FIELD_INDEX, AAX_SUCCESS, AAX_IParameter::CloneValue(), AAX_CEffectParameters::Controller(), AAX_IContainer::eStatus_Success, AAX_CEffectParameters::GenerateCoefficients(), AAX_IParameter::Identifier(), AAX_IController::PostPacket(), and AAX_CAtomicQueue< T, S >::Push().
ResetFieldData()
AAX_Result AAX_CMonolithicParameters::ResetFieldData (AAX_CFieldIndex inFieldIndex, void * oData, uint32_t inDataSize) const [virtual]
Called by the host to reset a private data field in the plug-in's algorithm.
This method is called sequentially for all private data fields on Effect initialization and during any `reset` event, such as priming for a non-real-time render. This method is called before the algorithm's optional initialization callback, and the initialized private data will be available within that callback via its context block.
See also
Algorithm initialization.
Warning
Any data structures that will be passed between platforms (for example, sent to a TI DSP in an AAX DSP plug-in) must be properly data-aligned for compatibility across both platforms. See AAX_ALIGN_FILE_ALG for more information about guaranteeing cross-platform compatibility of data structures used for algorithm processing.
Parameters
 in inFieldIndex The index of the field that is being initialized
 out oData The pre-allocated block of data that should be initialized
 in inDataSize The size of the data block, in bytes
Reimplemented from AAX_CEffectParameters.
References AAX_ASSERT, AAX_FIELD_INDEX, AAX_SUCCESS, AAX_SInstrumentPrivateData::mMonolithicParametersPtr, and AAX_CEffectParameters::ResetFieldData().
TimerWakeup()
AAX_Result AAX_CMonolithicParameters::TimerWakeup () [virtual]
Periodic wakeup callback for idle-time operations.
This method is called from the host using a non-main thread. In general, it should be driven at approximately one call per 30 ms. However, the wakeup is not guaranteed to be called at any regular interval - for example, it could be held off by a high real-time processing load - and there is no host contract regarding maximum latency between wakeup calls.
This wakeup thread runs continuously and cannot be armed/disarmed or by the plug-in.
Reimplemented from AAX_CEffectParameters.
References AAX_CEffectParameters::TimerWakeup().
StaticDescribe()
AAX_Result AAX_CMonolithicParameters::StaticDescribe (AAX_IEffectDescriptor * ioDescriptor, const AAX_SInstrumentSetupInfo & setupInfo) [static]
Static description callback
This method performs all of the basic context setup and pointer passing work
Parameters
 in,out ioDescriptor
 in setupInfo
References AAX_ASSERT, AAX_eConstraintLocationMask_DataModel, AAX_eMIDINodeType_Global, AAX_eMIDINodeType_LocalInput, AAX_eMIDINodeType_Transport, AAX_ePrivateDataOptions_DefaultOptions, AAX_eProperty_CanBypass, AAX_eProperty_Constraint_Location, AAX_eProperty_Constraint_MultiMonoSupport, AAX_eProperty_HybridInputStemFormat, AAX_eProperty_HybridOutputStemFormat, AAX_eProperty_InputStemFormat, AAX_eProperty_ManufacturerID, AAX_eProperty_OutputStemFormat, AAX_eProperty_PlugInID_AudioSuite, AAX_eProperty_PlugInID_RTAS, AAX_eProperty_ProductID, AAX_eProperty_UsesClientGUI, AAX_eProperty_UsesTransport, AAX_ERROR_NULL_OBJECT, AAX_eStemFormat_None, AAX_FIELD_INDEX, AAX_IComponentDescriptor::AddAudioBufferLength(), AAX_IComponentDescriptor::AddAudioIn(), AAX_IComponentDescriptor::AddAudioOut(), AAX_IComponentDescriptor::AddAuxOutputStem(), AAX_IComponentDescriptor::AddClock(), AAX_IEffectDescriptor::AddComponent(), AAX_IComponentDescriptor::AddDataInPort(), AAX_IComponentDescriptor::AddMeters(), AAX_IComponentDescriptor::AddMIDINode(), AAX_IComponentDescriptor::AddPrivateData(), AAX_IComponentDescriptor::AddProcessProc_Native(), AAX_IPropertyMap::AddProperty(), kMaxAdditionalMIDINodes, kMaxAuxOutputStems, AAX_SInstrumentSetupInfo::mAudiosuiteID, AAX_SInstrumentSetupInfo::mAuxOutputStemFormats, AAX_SInstrumentSetupInfo::mAuxOutputStemNames, AAX_SInstrumentSetupInfo::mCanBypass, AAX_SInstrumentSetupInfo::mGlobalMIDIEventMask, AAX_SInstrumentSetupInfo::mGlobalMIDINodeName, AAX_SInstrumentSetupInfo::mHybridInputStemFormat, AAX_SInstrumentSetupInfo::mHybridOutputStemFormat, AAX_SInstrumentSetupInfo::mInputMIDIChannelMask, AAX_SInstrumentSetupInfo::mInputMIDINodeName, AAX_SInstrumentSetupInfo::mInputStemFormat, AAX_SInstrumentSetupInfo::mManufacturerID, AAX_SInstrumentSetupInfo::mMeterIDs, AAX_SInstrumentSetupInfo::mMultiMonoSupport, AAX_SInstrumentSetupInfo::mNeedsGlobalMIDI, AAX_SInstrumentSetupInfo::mNeedsInputMIDI, AAX_SInstrumentSetupInfo::mNeedsTransport, AAX_SInstrumentSetupInfo::mNumAdditionalInputMIDINodes, AAX_SInstrumentSetupInfo::mNumAuxOutputStems, AAX_SInstrumentSetupInfo::mNumMeters, AAX_SInstrumentSetupInfo::mOutputStemFormat, AAX_SInstrumentSetupInfo::mPluginID, AAX_SInstrumentSetupInfo::mProductID, AAX_SInstrumentSetupInfo::mUseHostGeneratedGUI, AAX_IEffectDescriptor::NewComponentDescriptor(), AAX_IComponentDescriptor::NewPropertyMap(), and StaticRenderAudio().
StaticRenderAudio()
void AAX_CALLBACK AAX_CMonolithicParameters::StaticRenderAudio (AAX_SInstrumentRenderInfo *const inInstancesBegin[], const void * inInstancesEnd) [static]
Static RenderAudio (Called by the host)
Plug-ins should override AAX_CMonolithicParameters::RenderAudio()
Parameters
 in inInstancesBegin
 in inInstancesEnd
References AAX_ASSERT, AAX_IContainer::eStatus_Success, AAX_SInstrumentPrivateData::mMonolithicParametersPtr, AAX_CAtomicQueue< T, S >::Push(), and RenderAudio().
Referenced by StaticDescribe().
The documentation for this class was generated from the following files:
AAX_CMonolithicParameters.h
AAX_CMonolithicParameters.cpp